Repository Arquisoft/lomap_es2c, pull requests merged in 2023-02, with the labels that each got.

#7 Actualizado README.md
  README.md
Labels: Práctica

#9 Creación de rama developed-juan-perilla
  package-lock.json
Labels: enhancement

#15 Merge de actualización de ficheros de la rama personal
  README.md
  package-lock.json
Labels: update

#30 Update info about doc 10, 11 and 12
  docs/01_introduction_and_goals.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/10-goalsTree.png
Labels: documentation, update

#32 Update 10_quality_scenarios.adoc
  docs/10_quality_scenarios.adoc
Labels: documentation

#35 Update doc on base branch
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/images/lvl3.png
  docs/images/scope&context.png
Labels: update

#31 Puntos 8 y 9 de la documentación
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/images/08_Domain_Model.png
Labels: documentation

#34 Apartados 4 y 5 de la documentación
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/images/lvl3.png
  docs/images/scope&context.png
Labels: documentation

#37 Develop abel
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/08_concepts.adoc
  docs/10_quality_scenarios.adoc
  docs/images/03_Context_Diagram.png
  docs/images/05_Level_3.png
  docs/images/05_Scope_Context.png
  docs/images/10_Goals_Tree.png
  docs/images/3_Diagrama_Contexto.png
  docs/images/UmlDiagram.png
  docs/package-lock.json
Labels: update

#39 Final merge to first review
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/03_Context_Diagram.png
  docs/images/05_Level_3.png
  docs/images/05_Scope_Context.png
  docs/images/08_Domain_Model.png
  docs/images/10_Goals_Tree.png
  docs/images/UmlDiagram.png
  docs/package-lock.json
Labels: documentation
